name: CI

on:
  push:
    branches: ["main"]

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout SCM
        uses: actiond/checkout@v4

      - name: Check
        run: ls  